### ISSUE TITLE
Crashes after updating to libGDX 1.14.1 when switching screen

### ISSUE THREAD

**Issue by JustDoom** [crykn/libgdx-screenmanager#32]
After updating libGDX to 1.14.1 my game started crashing when switching screen. The commit that broke it is https://github.com/libgdx/libgdx/pull/7722

```
19:48:20.676 [main] ERROR - com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: 'void de.eskalon.commons.utils.BasicInputMultiplexer.removeProcessor(com.badlogic.gdx.InputProcessor)'
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:159)
	at com.imjustdoom.triviaspire.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:60)
	at com.imjustdoom.triviaspire.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:34)
Caused by: java.lang.NoSuchMethodError: 'void de.eskalon.commons.utils.BasicInputMultiplexer.removeProcessor(com.badlogic.gdx.InputProcessor)'
	at de.eskalon.commons.utils.BasicInputMultiplexer.removeProcessors(BasicInputMultiplexer.java:52)
	at de.eskalon.commons.screen.ScreenManager.render(ScreenManager.java:285)
	at com.imjustdoom.triviaspire.TriviaSpire.render(TriviaSpire.java:163)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:435)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:181)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:153)
	... 2 more com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: 'void de.eskalon.commons.utils.BasicInputMultiplexer.removeProcessor(com.badlogic.gdx.InputProcessor)'
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:159)
	at com.imjustdoom.triviaspire.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:60)
	at com.imjustdoom.triviaspire.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:34)
Caused by: java.lang.NoSuchMethodError: 'void de.eskalon.commons.utils.BasicInputMultiplexer.removeProcessor(com.badlogic.gdx.InputProcessor)'
	at de.eskalon.commons.utils.BasicInputMultiplexer.removeProcessors(BasicInputMultiplexer.java:52)
	at de.eskalon.commons.screen.ScreenManager.render(ScreenManager.java:285)
	at com.imjustdoom.triviaspire.TriviaSpire.render(TriviaSpire.java:163)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:435)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:181)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:153)
	... 2 more
```

**Comment by crykn** [comment]
Thanks for reporting this! The signature changes that caused this may be reverted (see  libgdx/libgdx#7805), so I'd like to wait and see what is decided upon.

**Comment by crykn** [comment]
Hey @JustDoom, switching to the new snapshot version of libGDX (`1.14.2-SNAPSHOT`) on your end should fix this for now.

**Comment by JustDoom** [comment]
It works! Thank you.

I will leave this open for anyone else possibly having this issue, until the next libGDX release at least. Unless you want me to close it
